name: Deploy Static Site to AWS

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Select Terraform Workspace
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            terraform workspace select dev || terraform workspace new dev
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            terraform workspace select staging || terraform workspace new staging
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            terraform workspace select prod || terraform workspace new prod
          fi

      - name: Plan Terraform Changes
        run: terraform plan -var-file="environments/${{ github.ref_name }}.tfvars"

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve -var-file="environments/${{ github.ref_name }}.tfvars"
